all:
  children:
    proxmox:
      hosts:
        192.168.15.43:
          ansible_connection: ssh
          ansible_user: "{{ lookup('env', 'ANSIBLE_USER') }}"
          ansible_password: "{{ lookup('env', 'ANSIBLE_PASSWORD') }}"