---
pve_servers:
  hosts:
    pve_server:
      ansible_host: 192.168.15.58 # Replace with your Hyper-V server IP
  vars:
    ansible_connection: winrm
    ansible_winrm_transport: ntlm # Change to basic or kerberos if needed
    ansible_winrm_scheme: http
    ansible_port: 5985
    ansible_user: administrator # Replace with your admin username
    ansible_password: "@dmin123Z" #  Password directly here for testing.  Use a variable or Ansible Vault in production