---
- hosts: proxmox
  become: true
  gather_facts: false # Desabilitamos a coleta de facts para reduzir a saída
  vars_files:
    - vars.yml
  tasks:
    - name: Get Proxmox version  # Get the Proxmox version
      ansible.builtin.command: pveversion -v
      register: proxmox_version
      changed_when: false

    - name: Print Proxmox version  # Print the output
      ansible.builtin.debug:
        msg: "Proxmox version: {{ proxmox_version.stdout }}"

    - name: Load variables from vars.yml
      include_vars:
        file: ../../vars.yml

    - name: Check if a VM with ID 100 exists
      ansible.builtin.uri:
        url: "https://{{ api_host }}:8006/api2/json/nodes/pve/qemu/100" # assumindo que o node é pve
        method: GET
        status_code: 200
        validate_certs: no
        headers:
          Authorization: "PVEAPIToken={{ api_user }}={{ api_password }}"
      register: vm_exists
      changed_when: false

    - name: Print VM existence status  # Print the result
      ansible.builtin.debug:
        msg: "VM 100 exists: {{ vm_exists.status == 200 }}"